### PR TITLE
Add T-Mobile shops JSON and match to API

### PR DESCRIPTION
**Pull request by StefanBrand**
See the comment on 5821d19 for the troubles I ran into...

### CODE REVIEW

**Comment by Roboe** [comment]
Uff, that's a tough one... Let me some time to understand it

**Comment by Roboe** [comment]
Where did you get the initial JSON? Did your T-Mobile contact give it to you as is and then you adapted it to our API?
We can make a conversor (and cleaner) with `node.js`, to get the data we want and discard the rest.
```javascript
/* node.js supports ECMAScript 2015 syntax */
const fs = require('fs');
const rawData = require(`tMobileShops.raw.json`);
const /* let */ netData = rawData.shops.map(functionToClearAndAdapt());
fs.writeFile('tMobileShops.json', netData);
```

About our API flaw, that's true. We need to review the `openingHours` part... :/

**Comment by StefanBrand** [comment]
> Where did you get the initial JSON? Did your T-Mobile contact give it to
 > you as is and then you adapted it to our API?

Exactly. I needed a lot of find-and-replace operations in atom.io (and 
[this great regex tutorial](https://www.regexone.com/)) to modify the 
file. I couldn't find a way to automize it and a Windows batch file 
wasn't really an option.

Where does the |node.js| script run then? In the browser at every 
startup of the map?

Am 30.09.2016 um 01:17 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
No. `node.js` is a runtime outside of the browser to run JavaScript code. Furthermore, it provides in-out functions for reading and writing files (and much more, I'm simplifying here). 
The idea is to run a node script locally (everytime we get an update) to generate the cleaned JSON to push to the repo.

**Comment by StefanBrand** [comment]
I'll create an issue in the other repo. See the following reference.

**Comment by StefanBrand** [comment]
Oh my, I think I messed something up... Ö I rebased my local copy of the fork because I wanted to do some minor improvements on the README and now ended up with some older commits being part of this PR (and the README-commit 45cc89c also being part of it)... Help!

**Comment by Roboe** [comment]
I've opened a new and clean PR for this matter. I'll close this, let's discuss the issue there: #32

**Pull request closed without merging**
