### PR TITLE
Remove markers clustering

### PR DESCRIPTION
**Pull request by Roboe**
This reverts commit 1dc401bddbb47cbeea77b8a6b4e4bb213f02a0c3.

Reasons, as we (@StefanBrand and I) chatted:
 - Clustering doesn't improve visiblity, but adds confusion. Most of the times, it groups markers too much distant of each other and removes visual hints of which zones have markers and which don't.
 - People are already used to dive into a bunch of markers in a map: zooming. Furthermore, we are able to filter groups of markers (groups, shops, etc) in the upper right panel. Clustering just lacks sense.

Preview:
https://roboe.github.io/fprsmap

### CODE REVIEW

**Comment by StefanBrand** [comment]
Do you think that performance gets worse with this (especially on FP1)?

This fixes #55.

**Comment by Roboe** [comment]
> Do you think that performance gets worse with this (especially on FP1)?

This should avoid a lot of computations from the clustering addon, doesn't it? I don't have a FP1, but my Moto E (LineageOS 14.1, very similar hardware) loads it just fine.

**Comment by StefanBrand** [comment]
Not the loading, but the panning. On a FP2 it also feels kinda laggy. I think because of the high number of markers that's displayed at once.

Maybe we can uncluster the markers only at a specific zoom level?
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 27. Mai 2017 15:41:55 MESZ schrieb "Roberto M.F." <notifications@github.com>:
>> Do you think that performance gets worse with this (especially on
>FP1)?
>
>This should avoid a lot of computations from the clustering addon,
>doesn't it? I don't have a FP1, but my Moto E (LineageOS 14.1, very
>similar hardware) loads it just fine.

**Comment by Roboe** [comment]
Let's see it canvas rendering solves the performance fall caused by the bunch of markers

**Comment by StefanBrand** [comment]
It might be a bit better. Zooming still lags though... 
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 28. Mai 2017 01:55:42 MESZ schrieb "Roberto M.F." <notifications@github.com>:
>Let's see it canvas rendering solves the performance fall caused by the
>bunch of markers

**Comment by Roboe** [comment]
No, you are right, clustering improves performance. See this: https://github.com/Leaflet/Leaflet.markercluster/blob/master/README.md#handling-lots-of-markers

We can leave clustering enabled, then, but it is still causing confusion —e.j. grouping markers on Spain with those on France, and falsely signaling there are no markers in Spain. How can we fix this?

**Comment by StefanBrand** [comment]
Leaflet/Leaflet.markercluster#749 and Leaflet/Leaflet.markercluster#521 give interesting ideas on improving this situation.

I thought about a different approach: Don't do clustering, but load country polygons into the map (possibly with a number of markers in that country). The idea would be that the markers don't appear at once, but only _after_ you click on the country or zoom in.

**Comment by Roboe** [comment]
Yeah, I don't like borders neither, but countries are the geographic organizations we have now.

Other solution may be placing the user at first in its aprox location (zoomed in), which feels creepy, IMO, and it's a privacy regression.

**Comment by StefanBrand** [comment]
According to the [Leaflet docs](http://leafletjs.com/reference-1.0.3.html#map-renderer), `canvas` rendering is on by default when the browser supports it.

Unfortunately I cannot check on Firefox for Android, but on desktop it can't have changed anything since `canvas` is supported by Firefox. (Though I cannot find a `<canvas>`-element in the webpage's source code...)

**Pull request closed without merging**
